name = "affirm-api"
main = "index.js"
compatibility_date = "2023-10-02"
compatibility_flags = ["nodejs_compat"]

# Specify the account ID (replace with your account ID)
account_id = "9098bac5e73248e51e75892b33f0b9c0"

# Define environment variables for different environments
[vars]
# You'll need to set these in the Cloudflare dashboard or via wrangler
# GEMINI_API_KEY = ""

# Or use secrets for more security (recommended)
# Run: wrangler secret put GEMINI_API_KEY

# Define routes if using Workers Sites
# [site]
# bucket = "./public" 